" 行番号の表示
set number
" ターミナルのタイトルをセット
set title
" 全角文字の幅を2文字に固定する
set ambiwidth=double
" タブ幅を4文字にする
set tabstop=4
" タブを半角スペースで挿入する
set expandtab
" 自動で生成するタブ幅を4文字にする
set shiftwidth=4
" 自動インデント
set smartindent
" 空白文字の可視化
set list
" 可視化した空白文字の表現
set listchars=tab:»-,trail:-,eol:↲,extends:»,precedes:«,nbsp:%
" 0で始まる数値を8進数として扱わない
set nrformats-=octal
" ファイル保存していなくても別のファイルを開けるようにする
set hidden
" 文字のないところにカーソル移動できるようにする
set virtualedit=block
" 次の行にカーソルの回り込みができるようにする
set whichwrap=b,s,[,],<,>
" バックスペースを空白などにも使えるようにする
set backspace=indent,eol,start
" クリップボードを共有
set clipboard=unnamedplus
